### ISSUE TITLE
Implement a more responsive navigation system

### ISSUE THREAD

**Issue by JacobDB** [JacobDB/new-site#21]
After seeing [okayNav], I think it's time to start looking at ways to implement a more dynamic, more responsive navigation system. It would need to meet the following goals:

- [ ] As the browser shrinks, or an admin adds links to the navigation, links at the end of the menu get moved in to an additional menu, underneath a `...` icon.
- [ ] Links within the additional menu still need to support dropdowns. Turn them in to flyouts once they're nested within the additional menu.
- [ ] It must be fully touch enabled. Take a look at my current menu script to understand how to accomplish this.
- [ ] There needs to be a JavaScript-free fallback. It doesn't need to be pretty, it should just stack links instead of hiding them in an additional menu.
- [ ] There should be variants set up for `-left`, `-right`, and `-center`, dictating alignment of various aspects of the menu.
- [ ] There should be a `-vertical` variant that supports accordion-style menus, again, optimized for touch. It's important that there's a fallback here, possible based on checkboxes and labels, as much as I hate them.
- [ ] There should be an `-app` variant that supports beautiful app-style animations and behavior, similar to the River Trails Park District site I've been working on.
- [ ] The last drop down, or the additional menu, should do it's best to avoid going off screen. This means aligning it to the edge of the navigation wrapper.
- [ ] It should also support more forgiving movement patterns [(see this article)](https://css-tricks.com/dropdown-menus-with-more-forgiving-mouse-movement-paths/).

More information:

- https://github.com/VPenkov/okayNav

**Comment by revxx14** [comment]
I may not be skilled enough to build this out myself. It's deceptively complex.
