### ISSUE TITLE
Integrate some PostCSS functionality

### ISSUE THREAD

**Issue by JacobDB** [JacobDB/new-site#24]
After finally reading about PostCSS, I think it's a good idea to start trying to integrate this in to my workflow. The following should be added to my gulpfile:
- [x] Automatic `px` fallback for `rem` units.
- [x] Lint stylesheets using custom rulesto ensure they're well coded.
- [ ] Integrate [cssnext](http://cssnext.io/), which allows use of some awesome future syntax.
- [ ] Integrate something that strips out all unused CSS. This may be more easily said than done, particularly with WordPress sites.

There's a lot more out there with PostCSS, but I think this is a good starting point. If everything goes well, I'll continue integrating more functionality.

More information: 
- http://webdesign.tutsplus.com/tutorials/postcss-deep-dive-what-you-need-to-know--cms-24535
- https://github.com/postcss/postcss
- http://cssnext.io/

**Comment by revxx14** [comment]
Just thumbed through a great article on this.

http://www.sitepoint.com/improving-the-quality-of-your-css-with-postcss/

**Comment by JacobDB** [comment]
I just had an interesting idea. I'm thinking it would make a lot of sense to make my "critical" css all the styles for the mobile version of the site. However, that's also the majority of the styles. So maybe it's more like... The styles required to make the top portion of the page load on a screen the size of a Nexus 5. That would cut down on a lot of the CSS required, including the mobile nav, footer, callouts, etc that appear on most sites.

https://github.com/addyosmani/critical

**Comment by JacobDB** [comment]
Closing this, it's better suited in separate tasks, and I've already addressed some of it.
