### ISSUE TITLE
Filter user content to add rel="noopener" to all links

### ISSUE THREAD

**Issue by JacobDB** [JacobDB/new-site#26]
A filter should be added to `the_content();` to add `rel="noopener"` to all links. This helps eliminate the possibility of XSS attacks. The below preg_match is untested, but I believe it should be a good starting point:

```
preg_match("/<a.*href=('|")[^"^'\r\n]*('|")[^>\r\n]*>/im", "", $the_content);`
```

This may only be necessary for links to external sites.

More information:

- https://mathiasbynens.github.io/rel-noopener/

**Comment by revxx14** [comment]
regex for matching links is `<a.*href=('|")[^"^'\r\n]*('|")[^>\r\n]*>`

**Comment by JacobDB** [comment]
https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/?utm_source=codropscollective
