### ISSUE TITLE
Document everything

### ISSUE THREAD

**Issue by JacobDB** [JacobDB/new-site#43]
My code needs to be well documented. Currently, it's a bit of a mess. Most of the comments I've seen use things like `@uses`, `@since`, etc. I'm not sure what that standard is called, but it needs to be researched further.

More information:
- http://docs.writethedocs.org/writing/beginners-guide-to-docs/
- https://css-tricks.com/annotating-critical-css/

**Comment by revxx14** [comment]
I started developing a [detailed contribution guide](https://github.com/revxx14/contribution-guide) but I never finished it. I may need to scrap it and start over, but that will need to wait until v1.0.0 is complete, as there are going to be some major changes.

I'd like to host this on a service like ReadTheDocs.org, or possibly as a wiki for this repository.

**Comment by JacobDB** [comment]
https://github.com/bradfrost/style-guide-guide

**Comment by JacobDB** [comment]
Closing in favor of #114
