### ISSUE TITLE
Look in to the possibility of removing reliance on jQuery

### ISSUE THREAD

**Issue by JacobDB** [JacobDB/new-site#48]
I'd really like to remove the reliance on jQuery, but I don't know enough plain JavaScript to make this feasible. I'm making a note of it, but this is more of a "far future" goal.

**Comment by revxx14** [comment]
I just found a pretty good resource on how to replace a decent number of jQuery functions with vanilla JS.

http://youmightnotneedjquery.com/

**Comment by revxx14** [comment]
I had a bit of a hard time tracking this one down, but here's a snippet that will let you wrap an element with vanilla JS:

http://www.mikedoesweb.com/2014/wrapping-an-element-in-vanilla-javascript/

**Comment by JacobDB** [comment]
Check in to using "swipe" for slideshows:

https://github.com/thebird/swipe

**Comment by JacobDB** [comment]
Very interesting jQuery alternative to consider http://zeptojs.com/

**Comment by JacobDB** [comment]
https://gomakethings.com/ditching-jquery/

**Comment by JacobDB** [comment]
Done :)
