### ISSUE TITLE
Replace FontAwesome CSS include with inline SVG

### ISSUE THREAD

**Issue by JacobDB** [JacobDB/new-site#49]
I'm imagining using something like `@@fa-search`, which the gulpfile would replace with inline SVG. This seems doable. The main concern is how to handle this within CSS. I try not to manually specify icons in CSS, but sometime's it's necessary.

I'll need to do some more research on inline SVG inside of a CSS file.

**Comment by revxx14** [comment]
I did a little more research and found there is in fact a way to insert SVG directly in a CSS file. Pretty awesome! http://stackoverflow.com/questions/10768451/inline-svg-in-css

**Comment by JacobDB** [comment]
Doesn't seem feasible at this point, closing for now.
