### ISSUE TITLE
Improve overlay functionality

### ISSUE THREAD

**Issue by JacobDB** [JacobDB/new-site#97]
- [ ] Eliminate custom modal stuff, replacing with a more elegant third-party system
- [ ] Set up touch controls for mobile navigation (swiping out for an app-like experience, see https://medium.com/outsystems-experts/gestures-glamour-setting-up-a-touch-menu-6d9b94039997
- [ ] Enable any element to "open" any other element, and focus any child of that element.

    i.e. `<button data-toggle=".menu-list" data-focus=".menu-list_link">`

**Comment by JacobDB** [comment]
The touch menu system is coming along nicely, but there are a few changes I still want to make:

- [ ] Remove reliance on `_notransition` class, instead opting to enable & disable transitions in JS.
- [ ] See if it would be possible to read the maximum opacity from CSS, rather than having to manually set it.
- [ ] See if `requestAnimationFrame()` can be changed to `request_animation_frame()`; I think this may be a method built in to JavaScript, so this may not be possible, but the fact that it's missing `window` in the code is throwing me off. https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame
- [ ] Focus the menu on touch end, if the menu is open, otherwise return focus to whatever was previously focused.
- [ ] Trap focus on the menu while it's open

**Comment by JacobDB** [comment]
Calling this good

**Comment by tspesh** [comment]
For your sake, for now, yes.  We’re actually meeting today about what we’re going to do with this though. Your most recent changes look good with the fields you used but we sometimes use more, and I’m not sure we are able to shrink the text anymore than we already have so we need to adjust on our end.

There will likely be some more work on this for you though honestly.  I’ll keep you posted.

-- 
Tim Speciale
Director, Technology and Business Operations
Skype: Tim.Speciale
BWW Media Group | Petri.com | Thurrott.com

**Comment by JacobDB** [comment]
@tspesh oh this is for my framework, no the project we've been working on, haha. Apparently you get email notifications since you're watching my repository :)
